name: test-can-build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  can-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go-Version
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "*/*.sum"

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Build Docker container
        run: just build
